# Fix missing imports in sales/views.py for pos_vip_status
# Run from your dashboard folder (where manage.py is)

$base64 = "CmltcG9ydCBvcwoKdmlld3NfcGF0aCA9IG9zLnBhdGguam9pbignc2FsZXMnLCAndmlld3MucHknKQppZiBub3Qgb3MucGF0aC5leGlzdHModmlld3NfcGF0aCk6CiAgICBwcmludCgnRVJST1I6ICcgKyB2aWV3c19wYXRoICsgJyBub3QgZm91bmQhJykKICAgIGV4aXQoMSkKCndpdGggb3Blbih2aWV3c19wYXRoLCAncicsIGVuY29kaW5nPSd1dGYtOCcpIGFzIGY6CiAgICBjb250ZW50ID0gZi5yZWFkKCkKCiMgTGlzdCBvZiBpbXBvcnRzIHdlIG5lZWQKbmVlZGVkID0gWwogICAgKCdmcm9tIGRqYW5nby5jb250cmliLmF1dGguZGVjb3JhdG9ycyBpbXBvcnQgbG9naW5fcmVxdWlyZWQnLCAnbG9naW5fcmVxdWlyZWQnKSwKICAgICgnZnJvbSBkamFuZ28uaHR0cCBpbXBvcnQgSnNvblJlc3BvbnNlJywgJ0pzb25SZXNwb25zZScpLAogICAgKCdmcm9tIGRqYW5nby51dGlscyBpbXBvcnQgdGltZXpvbmUnLCAndGltZXpvbmUnKSwKICAgICgnZnJvbSBkYXRldGltZSBpbXBvcnQgdGltZWRlbHRhJywgJ3RpbWVkZWx0YScpLAogICAgKCdmcm9tIGRqYW5nby5kYi5tb2RlbHMgaW1wb3J0IFN1bScsICdTdW0nKSwKICAgICgnZnJvbSBmYWNlX3JlY29nbml0aW9uX2FwcC5tb2RlbHMgaW1wb3J0IFJlY29nbml0aW9uTG9nJywgJ1JlY29nbml0aW9uTG9nJyksCl0KCmFkZGVkID0gW10KZm9yIGltcCwgY2hlY2sgaW4gbmVlZGVkOgogICAgaWYgY2hlY2sgbm90IGluIGNvbnRlbnQ6CiAgICAgICAgIyBGaW5kIGEgZ29vZCBwbGFjZSB0byBpbnNlcnQgLSBhZnRlciB0aGUgbGFzdCBpbXBvcnQgbGluZQogICAgICAgIGxpbmVzID0gY29udGVudC5zcGxpdCgnXG4nKQogICAgICAgIGxhc3RfaW1wb3J0X2lkeCA9IC0xCiAgICAgICAgZm9yIGksIGxpbmUgaW4gZW51bWVyYXRlKGxpbmVzKToKICAgICAgICAgICAgc3RyaXBwZWQgPSBsaW5lLnN0cmlwKCkKICAgICAgICAgICAgaWYgc3RyaXBwZWQuc3RhcnRzd2l0aCgnZnJvbSAnKSBvciBzdHJpcHBlZC5zdGFydHN3aXRoKCdpbXBvcnQgJyk6CiAgICAgICAgICAgICAgICBsYXN0X2ltcG9ydF9pZHggPSBpCiAgICAgICAgaWYgbGFzdF9pbXBvcnRfaWR4ID49IDA6CiAgICAgICAgICAgIGxpbmVzLmluc2VydChsYXN0X2ltcG9ydF9pZHggKyAxLCBpbXApCiAgICAgICAgICAgIGNvbnRlbnQgPSAnXG4nLmpvaW4obGluZXMpCiAgICAgICAgZWxzZToKICAgICAgICAgICAgY29udGVudCA9IGltcCArICdcbicgKyBjb250ZW50CiAgICAgICAgYWRkZWQuYXBwZW5kKGNoZWNrKQoKaWYgYWRkZWQ6CiAgICB3aXRoIG9wZW4odmlld3NfcGF0aCwgJ3cnLCBlbmNvZGluZz0ndXRmLTgnKSBhcyBmOgogICAgICAgIGYud3JpdGUoY29udGVudCkKICAgIHByaW50KCfinIUgQWRkZWQgbWlzc2luZyBpbXBvcnRzIHRvIHNhbGVzL3ZpZXdzLnB5OiAnICsgJywgJy5qb2luKGFkZGVkKSkKZWxzZToKICAgIHByaW50KCfinIUgQWxsIGltcG9ydHMgYWxyZWFkeSBwcmVzZW50IGluIHNhbGVzL3ZpZXdzLnB5JykK"
$bytes = [System.Convert]::FromBase64String($base64)
$py = [System.Text.Encoding]::UTF8.GetString($bytes)

# Backup
$ts = Get-Date -Format "yyyyMMdd_HHmmss"
Copy-Item -Path "sales\views.py" -Destination "sales\views.py.importfix.$ts" -ErrorAction SilentlyContinue

# Write and run Python script
[IO.File]::WriteAllText("_temp_fix.py", $py)
python "_temp_fix.py"
Remove-Item "_temp_fix.py"

Write-Host "✅ Done! Missing imports added to sales/views.py" -ForegroundColor Green
Write-Host "Now run: python manage.py runserver" -ForegroundColor Cyan
