# Fix missing imports in sales/views.py (BULLETPROOF VERSION)
# Run from your dashboard folder (where manage.py is)

$base64 = "CmltcG9ydCBvcwoKdmlld3NfcGF0aCA9IG9zLnBhdGguam9pbignc2FsZXMnLCAndmlld3MucHknKQppZiBub3Qgb3MucGF0aC5leGlzdHModmlld3NfcGF0aCk6CiAgICBwcmludCgnRVJST1I6ICcgKyB2aWV3c19wYXRoICsgJyBub3QgZm91bmQhJykKICAgIGV4aXQoMSkKCndpdGggb3Blbih2aWV3c19wYXRoLCAncicsIGVuY29kaW5nPSd1dGYtOCcpIGFzIGY6CiAgICBjb250ZW50ID0gZi5yZWFkKCkKCiMgQWxsIGltcG9ydHMgbmVlZGVkIGJ5IHBvc192aXBfc3RhdHVzIGFuZCBwb3RlbnRpYWxseSBvdGhlciB2aWV3cwppbXBvcnRzX3RvX2FkZCA9IFsKICAgICdmcm9tIGRqYW5nby5jb250cmliLmF1dGguZGVjb3JhdG9ycyBpbXBvcnQgbG9naW5fcmVxdWlyZWQnLAogICAgJ2Zyb20gZGphbmdvLmh0dHAgaW1wb3J0IEpzb25SZXNwb25zZScsCiAgICAnZnJvbSBkamFuZ28udXRpbHMgaW1wb3J0IHRpbWV6b25lJywKICAgICdmcm9tIGRhdGV0aW1lIGltcG9ydCB0aW1lZGVsdGEnLAogICAgJ2Zyb20gZGphbmdvLmRiLm1vZGVscyBpbXBvcnQgU3VtJywKICAgICdmcm9tIGZhY2VfcmVjb2duaXRpb25fYXBwLm1vZGVscyBpbXBvcnQgUmVjb2duaXRpb25Mb2cnLApdCgphZGRlZF9hbnkgPSBGYWxzZQpmb3IgaW1wIGluIGltcG9ydHNfdG9fYWRkOgogICAgIyBDaGVjayBpZiB0aGlzIHNwZWNpZmljIGltcG9ydCBzdHJpbmcgZXhpc3RzIGFueXdoZXJlCiAgICBpZiBpbXAgbm90IGluIGNvbnRlbnQ6CiAgICAgICAgIyBJbnNlcnQgYXQgdGhlIHZlcnkgdG9wLCBiZWZvcmUgZXZlcnl0aGluZyBlbHNlCiAgICAgICAgY29udGVudCA9IGltcCArICdcbicgKyBjb250ZW50CiAgICAgICAgcHJpbnQoJ0FkZGVkOiAnICsgaW1wKQogICAgICAgIGFkZGVkX2FueSA9IFRydWUKICAgIGVsc2U6CiAgICAgICAgcHJpbnQoJ0FscmVhZHkgZXhpc3RzOiAnICsgaW1wKQoKaWYgYWRkZWRfYW55OgogICAgd2l0aCBvcGVuKHZpZXdzX3BhdGgsICd3JywgZW5jb2Rpbmc9J3V0Zi04JykgYXMgZjoKICAgICAgICBmLndyaXRlKGNvbnRlbnQpCiAgICBwcmludCgnXG7inIUgc2FsZXMvdmlld3MucHkgZml4ZWQgLSBpbXBvcnRzIGFkZGVkIGF0IHRvcCcpCmVsc2U6CiAgICBwcmludCgnXG7inIUgQWxsIGltcG9ydHMgYWxyZWFkeSBwcmVzZW50JykKCiMgQWxzbyB2ZXJpZnkgcG9zX3ZpcF9zdGF0dXMgZXhpc3RzCmlmICdkZWYgcG9zX3ZpcF9zdGF0dXMnIGluIGNvbnRlbnQ6CiAgICBwcmludCgn4pyFIHBvc192aXBfc3RhdHVzIHZpZXcgZm91bmQnKQplbHNlOgogICAgcHJpbnQoJ+KaoO+4jyBwb3NfdmlwX3N0YXR1cyB2aWV3IE5PVCBmb3VuZCAtIHJ1biB1cGRhdGVfcG9zX2FwaS5wczEnKQo="
$bytes = [System.Convert]::FromBase64String($base64)
$py = [System.Text.Encoding]::UTF8.GetString($bytes)

# Backup
$ts = Get-Date -Format "yyyyMMdd_HHmmss"
Copy-Item -Path "sales\views.py" -Destination "sales\views.py.importfix.$ts" -ErrorAction SilentlyContinue

# Write and run Python script
[IO.File]::WriteAllText("_temp_fix2.py", $py)
python "_temp_fix2.py"
Remove-Item "_temp_fix2.py"

Write-Host "✅ Done! Now run: python manage.py runserver" -ForegroundColor Green
