# Update Base Template: Browser Notification Permission
# Run from your dashboard folder (where manage.py is)

$base64 = "CmltcG9ydCBvcwoKYmFzZV9wYXRoID0gb3MucGF0aC5qb2luKCd0ZW1wbGF0ZXMnLCAnYmFzZS5odG1sJykKaWYgbm90IG9zLnBhdGguZXhpc3RzKGJhc2VfcGF0aCk6CiAgICBwcmludCgnRVJST1I6ICcgKyBiYXNlX3BhdGggKyAnIG5vdCBmb3VuZCEnKQogICAgZXhpdCgxKQoKd2l0aCBvcGVuKGJhc2VfcGF0aCwgJ3InLCBlbmNvZGluZz0ndXRmLTgnKSBhcyBmOgogICAgY29udGVudCA9IGYucmVhZCgpCgppZiAnTm90aWZpY2F0aW9uLnBlcm1pc3Npb24nIGluIGNvbnRlbnQ6CiAgICBwcmludCgnTm90aWZpY2F0aW9uIHBlcm1pc3Npb24gc2NyaXB0IGFscmVhZHkgZXhpc3RzIGluIGJhc2UuaHRtbCcpCiAgICBleGl0KDApCgpqcyA9ICcnJzxzY3JpcHQ+Ci8vID09PT09IEJyb3dzZXIgTm90aWZpY2F0aW9uIFBlcm1pc3Npb24gKEZlYXR1cmUgRCkgPT09PT0KKGZ1bmN0aW9uKCl7CmlmKCJOb3RpZmljYXRpb24iIGluIHdpbmRvdyAmJiBOb3RpZmljYXRpb24ucGVybWlzc2lvbiA9PT0gImRlZmF1bHQiKXsKICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXsKICAgICAgICBOb3RpZmljYXRpb24ucmVxdWVzdFBlcm1pc3Npb24oKS50aGVuKGZ1bmN0aW9uKHApewogICAgICAgICAgICBjb25zb2xlLmxvZygiQnJvd3NlciBub3RpZmljYXRpb24gcGVybWlzc2lvbjoiLCBwKTsKICAgICAgICB9KTsKICAgIH0sIDMwMDApOwp9Cn0pKCk7Cjwvc2NyaXB0PicnJwoKaW5zZXJ0ZWQgPSBGYWxzZQppZiAnPC9ib2R5PicgaW4gY29udGVudDoKICAgIGNvbnRlbnQgPSBjb250ZW50LnJlcGxhY2UoJzwvYm9keT4nLCBqcyArICdcbjwvYm9keT4nKQogICAgaW5zZXJ0ZWQgPSBUcnVlCmVsc2U6CiAgICBjb250ZW50ICs9ICdcbicgKyBqcwoKd2l0aCBvcGVuKGJhc2VfcGF0aCwgJ3cnLCBlbmNvZGluZz0ndXRmLTgnKSBhcyBmOgogICAgZi53cml0ZShjb250ZW50KQpwcmludCgn4pyFIGJhc2UuaHRtbCB1cGRhdGVkIHdpdGggbm90aWZpY2F0aW9uIHBlcm1pc3Npb24gcmVxdWVzdCcpCg=="
$bytes = [System.Convert]::FromBase64String($base64)
$py = [System.Text.Encoding]::UTF8.GetString($bytes)

# Backup
$ts = Get-Date -Format "yyyyMMdd_HHmmss"
Copy-Item -Path "templates\base.html" -Destination "templates\base.html.backup.$ts" -ErrorAction SilentlyContinue

# Write and run Python script
[IO.File]::WriteAllText("_temp_base.py", $py)
python "_temp_base.py"
Remove-Item "_temp_base.py"

Write-Host "✅ Done! base.html updated with notification permission request" -ForegroundColor Green
