# Generated by Django 5.2.16 on 2026-08-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this customer is primarily associated with (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='face_recognition_app.branch'),
        ),
    ]
