# Generated by Django 5.2.16 on 2026-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_delete_dashboardstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
