# Generated by Django 5.2.16 on 2026-07-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_photo_customer_image_and_more'),
        ('face_recognition_app', '0006_camera_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Which branch this customer is primarily associated with (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='face_recognition_app.branch'),
        ),
    ]
