# Generated by Django 6.0.7 on 2026-07-19 17:10

import django.db.models.deletion
import django.utils.timezone
import face_recognition_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_customer_photo_customer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('webcam', 'Laptop Webcam'), ('usb', 'USB Camera'), ('rtsp', 'RTSP IP Camera'), ('dvr', 'DVR Stream')], default='webcam', max_length=20)),
                ('connection_string', models.CharField(default='0', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Cosine similarity score at time of recognition (0.0 - 1.0)')),
                ('camera_name', models.CharField(blank=True, help_text='Denormalized camera name, kept even if the Camera row is later deleted.', max_length=100)),
                ('recognized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to=face_recognition_app.models.recognition_snapshot_path)),
                ('was_vip_at_time', models.BooleanField(default=False)),
                ('whatsapp_notified', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='face_recognition_app.camera')),
                ('customer', models.ForeignKey(blank=True, help_text='Null when the recognized face did not match any known customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='customers.customer')),
            ],
            options={
                'ordering': ['-recognized_at'],
                'indexes': [models.Index(fields=['-recognized_at'], name='face_recogn_recogni_af3372_idx')],
            },
        ),
    ]
