# Generated by Django 5.2.16 on 2026-08-07 17:48

import django.db.models.deletion
import django.utils.timezone
import face_recognition_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code for this branch, e.g. DHK-01, CTG-02', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_threshold', models.FloatField(default=0.65, help_text='Cosine similarity threshold for a customer face match (0.0-1.0). Lower = more lenient matching.')),
                ('vip_min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum total purchase amount for a customer to be flagged VIP.', max_digits=12)),
                ('default_camera_source', models.CharField(default='0', help_text='Fallback camera source (index or RTSP/DVR URL) used when video_feed is called without a camera_id.', max_length=200)),
                ('employee_recognition_threshold', models.FloatField(default=0.6, help_text='Cosine similarity threshold for an employee/attendance face match (0.0-1.0).')),
                ('attendance_dedupe_seconds', models.IntegerField(default=300, help_text='Minimum seconds between two attendance log entries for the same employee.')),
                ('ai_vip_messages_enabled', models.BooleanField(default=True, help_text='If on, VIP arrival WhatsApp messages to the manager are AI-personalized using purchase history. If off, a plain template message is sent instead.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('webcam', 'Laptop Webcam'), ('usb', 'USB Camera'), ('rtsp', 'RTSP IP Camera'), ('dvr', 'DVR Stream')], default='webcam', max_length=20)),
                ('connection_string', models.CharField(default='0', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='face_recognition_app.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='face_recognition_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=3)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='attendance_snapshots/')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_recognition_app.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='face_recognition_app.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(help_text='Cosine similarity score at time of recognition (0.0 - 1.0)')),
                ('camera_name', models.CharField(blank=True, help_text='Denormalized camera name, kept even if the Camera row is later deleted.', max_length=100)),
                ('recognized_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to=face_recognition_app.models.recognition_snapshot_path)),
                ('was_vip_at_time', models.BooleanField(default=False)),
                ('whatsapp_notified', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='face_recognition_app.camera')),
                ('customer', models.ForeignKey(blank=True, help_text='Null when the recognized face did not match any known customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_logs', to='customers.customer')),
            ],
            options={
                'ordering': ['-recognized_at'],
                'indexes': [models.Index(fields=['-recognized_at'], name='face_recogn_recogni_af3372_idx')],
            },
        ),
    ]
