# Generated by Django 5.2.16 on 2026-07-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_threshold', models.FloatField(default=0.65, help_text='Cosine similarity threshold for a face match (0.0-1.0). Lower = more lenient matching.')),
                ('vip_min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum total purchase amount for a customer to be flagged VIP.', max_digits=12)),
                ('default_camera_source', models.CharField(default='0', help_text='Fallback camera source (index or RTSP/DVR URL) used when video_feed is called without a camera_id.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
