# Generated by Django 6.0.7 on 2026-07-23 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='attendance_dedupe_seconds',
            field=models.IntegerField(default=300, help_text='Minimum seconds between two attendance log entries for the same employee (avoids spamming logs while someone stands in frame).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='employee_recognition_threshold',
            field=models.FloatField(default=0.6, help_text='Cosine similarity threshold for an employee/attendance face match (0.0-1.0).'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='recognition_threshold',
            field=models.FloatField(default=0.65, help_text='Cosine similarity threshold for a customer face match (0.0-1.0). Lower = more lenient matching.'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=3)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='attendance_snapshots/')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_recognition_app.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='face_recognition_app.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
