# Generated by Django 6.0.7 on 2026-07-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_employee_systemsettings_attendance_dedupe_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_vip_messages_enabled',
            field=models.BooleanField(default=True, help_text='If on, VIP arrival WhatsApp messages to the manager are AI-personalized using purchase history. If off, a plain template message is sent instead.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='attendance_dedupe_seconds',
            field=models.IntegerField(default=300, help_text='Minimum seconds between two attendance log entries for the same employee.'),
        ),
    ]
