# Generated by Django 5.2.16 on 2026-07-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beverage', 'Beverage'), ('Food', 'Food'), ('Snack', 'Snack'), ('Electronics', 'Electronics'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
